name: Clear History and Deploy

on:
  schedule:
    # Runs at 00:00 UTC every sunday
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the current content
        uses: actions/checkout@v2
        with:
          ref: deploy  # Checkout the deploy branch (or whatever branch you use for deployment)

      - name: Remove old Git history
        run: |
          rm -rf .git  # Removes the existing Git history
      - name: Initialize new Git repository
        run: |
          git init
          git config user.name "thewanderingallison"
          git config user.email "actions@github.com"
      - name: Add all files
        run: |
          git add .
          git commit -m "Deploy latest version"
      - name: Force push to GitHub Pages branch (deploy)
        run: |
          git remote add origin https://x-access-token:${{ secrets.CLEAR_TOKEN }}@github.com/thewanderingallison/thewanderingallison.github.io.git
          git branch -M deploy
          git push -f origin gh-pages  # Force push to overwrite history
